### ISSUE TITLE
"The request does not support the instances `<instance>` which are in operation or in a special state."

### ISSUE THREAD

**Issue by DavidR91** [terraform-providers/terraform-provider-tencentcloud#343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20 (Cloud)

Not sure how to find out what version of the tencent provider is being used?

### Affected Resource(s)

* tencentcloud_key_pair
* tencentcloud_instance

### Terraform Configuration Files

```hcl
resource "tls_private_key" "example" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "tencentcloud_key_pair" "example_pair" {
  key_name   = "example_key"
  public_key = tls_private_key.example.public_key_openssh
}

resource "tencentcloud_instance" "example" {
  instance_name              = "example"
  key_name                   = tencentcloud_key_pair.example_pair.id

[...]
```

### Debug Output
[Pending]

### Expected Behavior
I've been using `tls_private_key` to generate keys for my instance, and I expect that after the initial provision the key is detected as the same and plan/apply should make no change

### Actual Behavior
The key is constantly detected as changed after the initial provision is completed, despite the fact the key value will be remaining the same:

```
# module.example_module.tencentcloud_instance.example will be updated in-place
  ~ resource "tencentcloud_instance" "example" {

        [...]

      ~ key_name                   = "skey-rpel9jgb" -> (known after apply)

        [...]
    }

  # module.example_module.tencentcloud_key_pair.example must be replaced
-/+ resource "tencentcloud_key_pair" "example" {
      ~ id         = "skey-rpel9jgb" -> (known after apply)
        key_name   = "example_key"
        project_id = 0
      ~ public_key = <<~EOT # forces replacement
            ssh-rsa AAAA.....
        EOT
    }
```

If you attempt to apply this, the result is:

```
Error: [TencentCloudSDKError] Code=InvalidInstance.NotSupported, Message=The request does not support the instances `<instance>` which are in operation or in a special state., RequestId=3fa03f99-70c0-458d-9d8d-00b6bfa9e713
```

I don't know what this means because from what I can see, the instance is running and operating correctly (e.g. it is not shut down or in any special state)

### Steps to Reproduce
* Use a TLS key to generate a tencentcloud_key_pair and use the key pair for the VM
* After initial creation the plan detects the key as changing constantly

### Important Factoids
* Provisioning via Terraform cloud
* AWS provisions using the same pattern (TLS key -> key pair -> VM) do not trigger re-provision which is why I expect this to work

**Comment by oliverpei** [comment]
Hi @DavidR91 , sorry for the trouble. We have fixed the bug, the next release will be ok.

**Comment by oliverpei** [comment]
#345

**Comment by likexian** [comment]
Hello @DavidR91 
This has been released in v1.30.4, please have a try.

**Comment by DavidR91** [comment]
@oliverpei @likexian sorry to be a pain but I don't think this is quite fixed, I still see this problem unless I do this:

```
lifecycle {
    ignore_changes = [ public_key ]
  }
```

Still don't have useful debug output but I did notice that the Tencent keypair strips or ignores the comment at the end of the key, for example:

```
....vJRRZSMMWBbGYkI4tRXYXsy7mHfxdP3xuRoZ3PMVUkcLdmdafHO7+T4xVSFQmE9rXkWzsmit7xRSQ4eUHtOAMDCThgJx0m6h+ObqiqHzw== rsa-key-20200218
```

(the ` rsa-key-20200218` part)

Is it the addition of this comment onto the public key each time that triggers the provider to detect it as changed? (Because the key in the state is stored without the comment?)

**Comment by oliverpei** [comment]
@DavidR91 The comment may be modified, so the key in the state is stored without the comment, but there is a bug when comparing the input keypair with state.
This has been released in v1.30.5, please have a try. Thanks!
